### ISSUE TITLE
Remove hard coded modules within most rules

### ISSUE THREAD

**Issue by slsevilla** [CCBR/exome-seek#15]
# Problem
Most of the rules within the pipeline have hard coded module versions that are not being pull from the partition / host specific configuration file

The rules affected are below (workflow/rules):
- cnv.smk
- ffpe.smk
- gatk_vqsr.smk
- germline.smk
- qc_human.smk
- qc_mm10.smk
- qc
- somatic_snps.paired.smk
- somatic_snps.tumor_only.smk
- somatic_snps.common.smk
- trim_map_preprocess.smk

# Solution
For each of the above affected rules
- [x] if the module is not part of the config, then add it
- [x] If it is part of the config and there is no conflict in version numbers, then remove hard coding and update rule to load version from the config (see below)
- [ ] If is part of the config and there is a conflict in versions, update to the most recent version available on rhel8 and test there are no errors emerging

# Notes
The updates should follow the nomenclature, based on the nesting:
```
{
   "tools": {
        "trimmomatic": {
            "version": "0.39"
        },
```

```
envmodules:
        TOOLS["trimmomatic"]["version"]
```
Feel free to also change the nesting of the json if you'd rather something cleaner:
```
{
   "tools": {
        "trimmomatic": "0.39"
        },
```
which would then read within the rules:
```
envmodules:
        TOOLS["TRIMMOMATIC"]
```

**Comment by samarth8392** [comment]
The file `tools.rhel8.json` was created with the following structure:
```
{
   "tools": {
        "trimmomatic": {
            "version": "0.39",
            "modname": "trimmomatic/0.39"
        },
```

Then, this new `tools.rhel8.json` file was appended to the config file by updating the `run.py` 

```
    required = {
        # Base configuration file
        "base": os.path.join(repo_path,'config','config.json'),
        # Template for project-level information
        "project": os.path.join(repo_path,'config','templates','project.json'),
        # Template for genomic reference files
        # User provided argument --genome is used to select the template
        "genome": genome_config,
        # Template for tool information
        "tools": os.path.join(repo_path,'config','templates','tools.rhel8.json'),
    }

```

Finally, the modname was called in the snakemake rules like:
```
envmodules:
        config['tools']['freec']['modname'],
        config['tools']['samtools']['modname'],
        config['tools']['bedtools']['modname'],
        config['tools']['R']['modname']
```
