### ISSUE TITLE
Update pipeline to allow for 'mouse' as species

### ISSUE THREAD

**Issue by slsevilla** [CCBR/exome-seek#7]
Problem:
- Currently the pipeline is hard coded for homo_sapiens for specific features, although mouse is a selectable species during 'run'.

Solution:
- Update pipeline so all features either can accept either species OR turn off feature and remove hard coding

**Comment by escauley** [comment]
To answer your question simply, it is hard-coded in the script `vcf2maf_wrapper.bash`

More info:

Based on my limited knowledge of the pipeline, it appears to me that mm10 is referenced in the script (based on the output of my run into the scratch folder):

`/scratch/cluster_scratch/cauleyes/tests/2023-03-30/WES_TNpairs_hg38/workflows/vcf2maf_wrapper.bash` 

which provides the parameters, including 'ncbi_build' where mm10 can be an option, to the script 

`vcf2maf.pl` (not sure where this is located exactly)

The script `vcf2maf_wrapper.bash` gathers paths from 

`/scratch/cluster_scratch/cauleyes/tests/2023-03-30/WES_TNpairs_hg38/config.json` 

including 'VEPRESOURCEBUNDLEPATH' where is assumes the mm10 reference files will be held, this path is:

`/mnt/projects/CCBR-Pipelines/genomes/Exome-seek/hg38/vcf2maf`

I will keep digging for other instances of mm10 references files being asked for, but so far this is what brought up the issue to begin with

**Comment by slsevilla** [comment]
Perfect! Thanks @escauley.

**Comment by slsevilla** [comment]
Paths have been updated for these scripts with commit 3c013d3a51d9d6dc5f1d183a0fae53956ee430bd
